services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - spriggle-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Load environment variables from .env file
    networks:
      - spriggle-net

networks:
  spriggle-net: